### PR TITLE
Bind default dispatchers automatically

### PR DESCRIPTION
**Pull request by glung**
https://github.com/soundcloud/lightcycle/issues/36

### CODE REVIEW

**Comment by NikoYuwono** [comment]
How about `SupportFragmentLightCycleDispatcher.java` ?

**Comment by glung** [comment]
oops thx

**Comment by NikoYuwono** [comment]
You are welcome!  
Looks good to me! :+1:

**Comment by glung** [comment]
Thx. I'll try to release next week.

**Pull request merged**
